# -*- coding: utf-8 -*-
"""Unemployment Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cUY8MpzLxjntfQbmd6OpeBtq3iGUEByF
"""

#importing the all necessary packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

#reading the dataset in CSV format
data = pd.read_csv("Unemployment in India.csv")
data

#removing the Nan values
data = data.dropna()

#gives the information about each adn every feature in the dataset
data.info

#gives the description of dataset
data.describe()

data[' Date'] = pd.to_datetime(data[' Date'])

#displaying the visualization between the unemployment rate and on particular date using barplot
plt.figure(figsize=(15,5))
plt.bar(data[' Date'], data[' Estimated Unemployment Rate (%)'])
plt.xlabel('Date')
plt.ylabel('Unemployment Rate')
plt.title('Unemployment Rate in India')
plt.show()

#displaying the advanced visualization between the unemployment rate and on particular date
plt.figure(figsize=(15,5))
sns.lineplot(x=' Date',y = ' Estimated Unemployment Rate (%)',data=data)

#caluclating the mean and median of unemployment rate
mean_unemployment = data[' Estimated Unemployment Rate (%)'].mean()
median_unemployment = data[' Estimated Unemployment Rate (%)'].median()
print('Mean Unemployment Rate: ',{mean_unemployment})
print('Median Unemployment Rate:' ,{median_unemployment})



data2.info

#displaying the visualization between the unemployment rate and on particular date during covid-19 using barplot
plt.figure(figsize=(15,5))
plt.bar(data2[' Date'],data2[' Estimated Unemployment Rate (%)'])
plt.xlabel("Date")
plt.ylabel("Unemployment Rate")
plt.title("Unemployment rate Upto 11-2020")
plt.show()

#displaying the advanced visualization between the unemployment rate and  date during covid-19
plt.figure(figsize=(15,5))
sns.lineplot(x=' Date',y = ' Estimated Unemployment Rate (%)',data=data2)

#caluclating the mean and median of unemployment rate during covid-19
mean_unemployment = data2[' Estimated Unemployment Rate (%)'].mean()
median_unemployment = data2[' Estimated Unemployment Rate (%)'].median()
print('Mean Unemployment Rate during Covid-19:', {mean_unemployment})
print('Median Unemployment Rate during Covid-19: ',{median_unemployment})